config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :reservations
  resources :users, except: :new
  resources :venues
  root 'sessions#home', as: 'home'

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'


  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create', as: 'registration'
  get '/my_venues', to: 'venues#my_venues', as: 'my_venues'
  get '/host_reservations', to: 'reservations#host_reservations', as: 'host_reservations'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :venue
  has_one :host, through: :venue, :foreign_key => "host_id"
  has_many :reservations
  has_many :renters, through: :reservations, :foreign_key => :renter_id
  has_many :images, through: :venue
  # has_many :reviews

  validates :available_start_date, presence: {message: 'Please enter a start date'}
  validates :available_end_date, presence: {message: 'Please enter an end date'}
  validates :price, presence: {message: "Please enter an amount"}
  validates :price, numericality: {message: "Please enter a numeric value"}

  validate :no_overlap, :start_before_end

  def no_overlap
    # checks if there are listings conflicting prior to listing creation
    current_listings = Listing.where(venue_id: self.venue.id)
    current_listings.each do |current_listing|
      if self.available_start_date <= current_listing.available_end_date && self.available_end_date >= current_listing.available_start_date
        errors.add(:no_overlap, "There are listing(s) conflicts")
      end
    end
  end

  def start_before_end
    if self.available_end_date < self.available_start_date
      errors.add(:invalid_date_range, "The listing start date must be before the end date")
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authorize, except: [:show, :index]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def show
    @listing = Listing.find(params[:id])
    # @listing.each do |list|
    #   @list_dates = []

  end

  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new
  end

  def create
    listing = Listing.new(listing_params)
    if listing.save
      redirect_to venue_path(listing_params[:venue_id])
    else
      redirect_to venue_path(listing_params[:venue_id]), notice: listing.errors.full_messages.join(". ")
    end

  end

  def edit #delete
    @listing = Listing.find(params[:id])
  end

  def update #delete
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)
    redirect_to listing_path(@listing)
  end

  def destroy
    listing = Listing.find(params[:id])
    # venue_id = @listing.venue_id
    # listing.reservations.destroy_all
    listing.reservations.each do |res|
      CancellationMailer.cancellation_email(res.host).deliver
      CancellationMailer.cancellation_email(res.renter).deliver
      res.destroy
    end
    listing.destroy
    @listings = Venue.find(listing.venue_id).listings
    respond_to do |format|
      format.js
    end
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:venue_id, :available_start_date, :available_end_date, :available_start_time, :available_end_time, :price)
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
This page should not exist or be used - only make a new listing through the venue.

<%= form_for(@listing) do |f| %>

<p><%= f.label :venue_id %>
<%= f.number_field :venue_id %><p>

<p><%= f.label :available_start_date %>
<%= f.date_select :available_start_date %><p>

<p><%= f.label :available_start_time %>
<%= f.time_select :available_start_time, {ampm: true, minute_step: 15} %><p>

<p><%= f.label :available_end_date %>
<%= f.date_select :available_end_date %><p>

<p><%= f.label :available_end_time %>
<%= f.time_select :available_end_time, {ampm: true, minute_step: 15} %><p>

<p><%= f.label :price %>
<%= f.text_field :price %><p>

<p><%= f.submit %></p>

<% end %>

app/views/listings/_venue_listings.html.erb
<% listings.each do |listing| %>
  Listing ID: <%= listing.id %> <br>
  Available Dates: <%= listing.available_start_date.strftime("%B %e, %Y") %> - <%= listing.available_end_date.strftime("%B %e, %Y") %> <br>
  <%= link_to "Delete", listing_path(listing), method: :delete, remote: true %> <br> <br>
<% end %>

app/views/listings/destroy.js.erb
$("div#venue-listings").html("<%=j render(partial: 'venue_listings', locals: { listings: @listings }) %>")

app/views/listings/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/listings/index.html.erb
<h1>Listings Index</h1>
<ul>
  <% @listings.each do |listing| %>
    <li><%= link_to listing.venue.name, listing_path(listing) %>
      <ul>
        <li>Available Dates: <%= listing.available_start_date.strftime("%B %e, %Y") %> - <%= listing.available_end_date.strftime("%B %e, %Y") %></li>
        <li>Available Hours: <%= listing.available_end_time.strftime("%H:%M") %> - <%= listing.available_end_time.strftime("%H:%M") %></li>
      </ul>
    </li>
  <% end %>
</ul>

<%= link_to "Add a Listing", new_listing_path %>

app/views/listings/new.html.erb
<h1>Create a New Listing</h1>

<%= render 'form' %>

app/views/listings/show.html.erb
<h1>Show</h1>
<ul>
  <li><%= link_to @listing.venue.name, venue_path(@listing.venue) %>
    <ul>
      <li>Available Dates: <%= @listing.available_start_date.strftime("%B %e, %Y") %> - <%= @listing.available_end_date.strftime("%B %e, %Y") %></li>
      <li>Available Hours: <%= @listing.available_start_time.strftime("%H:%M") %> - <%= @listing.available_end_time.strftime("%H:%M") %></li>
    </ul>
  </li>
</ul>

<%= link_to "Edit Listing", edit_listing_path(@listing) %>
<%= link_to "Remove Listing", listing_path(@listing), method: :delete %>

<div id="calendar_lis" data-listing-id=<%= @listing.id %>></div>