config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :reservations
  resources :users, except: :new
  resources :venues
  root 'sessions#home', as: 'home'

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'


  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create', as: 'registration'
  get '/my_venues', to: 'venues#my_venues', as: 'my_venues'
  get '/host_reservations', to: 'reservations#host_reservations', as: 'host_reservations'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validate :date_is_valid, :no_reservation_conflicts, :start_before_end
    validates :listing_id, presence: {message: 'Please enter a listing id'}
    validates :renter_id, presence: {message: 'Please enter a renter id'}
    validates :start_date, presence: {message: 'Please enter a start date'}
    validates :end_date, presence: {message: 'Please enter an end date'}



  belongs_to :listing
  has_one :venue, through: :listing
  # delegates: :venue, to: :listing??
  has_one :host, through: :venue, :foreign_key => "host_id"
  belongs_to :renter, :foreign_key => "renter_id", :class_name => "User"

  # review?



 def date_is_valid
   # reservation request falls within listing availability dates
   if self.start_date < self.listing.available_start_date || self.end_date > self.listing.available_end_date
     errors.add(:date_is_invalid, "Reservation date must be within the listing dates")
   end
 end

 def start_before_end
   if self.end_date < self.start_date
     errors.add(:invalid_date_range, "The start date must be before the end date")
   end
 end


 def no_reservation_conflicts
   # appends error if reservation request conflicts with other confirmed reservations for the listing
   confirmed_reservations = Reservation.where(listing_id: self.listing.id, confirmed: true)
   confirmed_reservations.each do |confirmed_reservation|
     if self.start_date <= confirmed_reservation.end_date && self.end_date >= confirmed_reservation.start_date
       errors.add(:reservation_conflicts, "There are reservation(s) conflicts")
     end
   end
 end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authorize
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
  end

  def new
    @reservation = Reservation.new
  end

  def create
    # reservation_creator = ReservationCreator.new(params)
    # reservation_creator.create_reservation
    # if reservation_creator.valid?
    #   redirect_to reservation_path(reservation_creator.reservation)
    # else
    #   redirect_to venue_path(Venue.find(venue_id)), notice: reservation_creator.notice )
    # end

    #listing.find_by instead of .where to return just one object

    #makes a new reservation (not yet saved! with the reqested dates)
    reservation = Reservation.new(reservation_params)
    # set venue_id with params
    venue_id = params[:reservation][:venue_id]
    #use venue_id to run ActiveRecord query to locate the one listing (if it exists) that encompasses the desired reservation date rage
    listing = Listing.where("venue_id = ? AND available_start_date <= ? AND available_end_date >= ?", venue_id, reservation.start_date, reservation.end_date) #looks up any listings
    # if there exists a listing, set renter_id to current_user and associate reservation listing
    if listing != []
      reservation.renter_id = current_user.id
      reservation.listing = listing[0]
        # run save to run reservation validations
        if reservation.save
          ReservationRequestMailer.reservation_request_email(reservation.host).deliver
          redirect_to reservation_path(reservation)
        else
          # redirect to venue show page if cannot save
          # binding.pry
          redirect_to venue_path(Venue.find(venue_id)), notice: reservation.errors.full_messages.join(". ")
        end
    else
      redirect_to venue_path(Venue.find(venue_id)), notice: "Please select dates where there is a listing" #should be render
    end
    # set up email and date verification/error message conditional for .save

  end

  def show

  end

  def host_reservations
    @user = current_user

  end

  def edit
  end

  def update
    @reservation.update(reservation_params)
    if @reservation.errors.any?
      redirect_to reservation_path(@reservation), notice: @reservation.errors.full_messages.join(". ")
    else
      # send different mailers based on if udpate is confirmation vs. some other modification
      if params[:reservation][:confirmed]
        ReservationConfirmationMailer.reservation_confirmation_email(@reservation.renter).deliver
      else
        ReservationUpdateMailer.reservation_update_email(@reservation.host).deliver
      end
      redirect_to reservation_path(@reservation)
    end
  end

  def destroy
    ReservationCancellationNotifier.execute(@reservation)
    if @reservation.host.id == current_user.id
      redirect_to host_reservations_path, notice: "This reservation has been deleted!"
    elsif @reservation.renter_id == current_user.id
      redirect_to reservations_path, notice: "This reservation has been deleted!"
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :start_time, :end_time, :confirmed, :comment)
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/edit.html.erb
<h1>Modify your reservation</h1>

<%= form_for @reservation do |f| %>

<%= f.hidden_field :listing_id, value: @reservation.listing_id %>
<br>
<%= f.hidden_field :renter_id, value: @reservation.renter_id %>
<br>
<%= f.label :start_date %>
<%= f.date_select :start_date %>
<br>
<%= f.label :end_date %>
<%= f.date_select :end_date %>
<br>
<%= f.hidden_field :confirmed?, value: false %>
<%= f.submit %>


<% end %>
<%= link_to "Cancel reservation", reservation_path(@reservation), method: "delete" %>

app/views/reservations/host_reservations.html.erb
<h1>Host Reservations</h1>
  <div id="calendar_res_h"></div>

  <% if @user.pending_host_reservations.count == 0 && @user.confirmed_host_reservations.count == 0 %>
    <h3>There are no reservations for YourSpace! <%= link_to "List YourSpace", new_venue_path %></h3>
  <% end %>

  <% if @user.pending_host_reservations.length > 0 %>
    <h3>Pending Reservations for YourSpace</h3>
      <%@user.pending_host_reservations.each do |res| %>
        <strong><%= "#{res.renter.first_name} #{res.renter.last_name}" %></strong> wants to rent <strong><%= link_to res.listing.venue.name, venue_path(res.listing.venue) %></strong>. <br>
        <strong>Start Date: </strong><%= res.start_date.strftime("%B %e, %Y") %> <br>
        <strong>End Date: </strong><%= res.end_date.strftime("%B %e, %Y") %> <br>

        <%= form_for(res) do |f|%>
          <%= f.hidden_field :confirmed, :value => true %>
          <%= f.submit "Confirm Reservation", data: { confirm: "Confirm this reservation?" } %> <br>
        <% end %>
          <%= button_to "Cancel Reservation", reservation_path(res), method: :delete, data: { confirm: "Cancel this reservation?" } %> <br>
      <% end %>
  <% end %>

  <% if @user.confirmed_host_reservations.length > 0 %>
    <h3>Confirmed Reservations for YourSpace</h1>
      <% @user.confirmed_host_reservations.each do |res| %>
        <%= link_to res.listing.venue.name, reservation_path(res) %> <br>
        <strong>Reservaton ID: </strong><%= res.id %> <br>
        <strong>Renter: </strong><%= "#{res.renter.first_name} #{res.renter.last_name}" %> <br>
        <strong>Start Date: </strong><%= res.start_date.strftime("%B %e, %Y") %> <br>
        <strong>End Date: </strong><%= res.end_date.strftime("%B %e, %Y") %> <br>
        <%= button_to "Cancel Reservation", reservation_path(res), method: :delete, data: { confirm: "Cancel this reservation?" } %> <br>
      <% end %>
  <% end %>

app/views/reservations/index.html.erb
<h1>Renter Reservations</h1>
  <div id="calendar_res_r"></div>

  <% if @user.confirmed_renter_reservations.count == 0 && @user.pending_renter_reservations.count == 0 %>
    <h3>You have no places booked! <%= link_to "See Available Venues", venues_path %></h3>
  <% end %>

  <% if @user.pending_renter_reservations.length > 0 %>
  <h3>Pending Renter Reservations</h3>
    <% @user.pending_renter_reservations.each do |res| %>
      <strong>Venue: </strong><%= link_to res.listing.venue.name, reservation_path(res) %> <br>
      <strong>Host: <strong><%= "#{res.listing.venue.host.first_name} #{res.listing.venue.host.last_name}" %></strong> <br>
      <strong>Start Date: </strong><%= res.start_date.strftime("%B %e, %Y") %> <br>
      <strong>End Date: </stong><%= res.end_date.strftime("%B %e, %Y") %> <br>
      <%= button_to "Cancel Reservation", reservation_path(res), method: :delete, data: { confirm: "Cancel this reservation?" } %> <br>
    <% end %>
  <% end %>

  <% if @user.confirmed_renter_reservations.length > 0 %>
    <h3>Confirmed Renter Reservations</h1>
      <% @user.confirmed_renter_reservations.each do |res| %>
        <%= link_to res.listing.venue.name, reservation_path(res) %> <br>
        <strong>Reservaton ID: </strong><%= res.id %> <br>
        <strong>Host: </strong><%= "#{res.listing.venue.host.first_name} #{res.listing.venue.host.last_name}" %> <br>
        <strong>Start Date: </strong><%= res.start_date.strftime("%B %e, %Y") %> <br>
        <strong>End Date: </strong><%= res.end_date.strftime("%B %e, %Y") %> <br>
        <%= button_to "Cancel Reservation", reservation_path(res), method: :delete, data: { confirm: "Cancel this reservation?" } %> <br>
      <% end %>
  <% end %>

app/views/reservations/new.html.erb
<h1>Make a reservation</h1>

<%= form_for @reservation do |f| %>
<p>
  note: ideally new reservation form should sit on listing page (pass listing_id hidden field instead)
</p>
<%= f.label :listing_id %>

<%= f.number_field :listing_id %>
<br>
<p>
  note: renter_id from session id (also hidden field)
</p>
<%= f.label :renter_id %>
<%= f.number_field :renter_id %>
<br>

<%= f.label :start_date %>
<%= f.date_select :start_date %>
<br>
<%= f.label :end_date %>
<%= f.date_select :end_date %>
<br>

<%= f.submit %>


<% end %>

app/views/reservations/show.html.erb
<% if @reservation.host.id == current_user.id %>
  <h1>Your venue has been booked by <%= @reservation.renter.first_name %>. </h1>
    Start Date: <%= @reservation.start_date %> <br>
    End Date: <%= @reservation.end_date %> <br>
    <% if @reservation.confirmed == false %>
      This reservation has not been confirmed. <br>
      <%= form_for(@reservation) do |f|%>
      <%= f.hidden_field :confirmed, :value => true %>
      <%= f.submit "Confirm Reservation" %> <br>
      <% end %>
      <%= link_to "Cancel Reservation", reservation_path(@reservation), method: :delete %> <br>
    <% else%>
      This reservation has been confirmed. <br>
    <%= link_to "Cancel Reservation", reservation_path(@reservation), method: :delete %> <br>
    <% end %>
<% else%>
  <% if @reservation.confirmed == false %>

    <h1> Hello, <%= @reservation.renter.first_name %>. Your reservation at <%= @reservation.venue.name %> is pending. A representative will be in touch shortly. </h1>
    Start Date: <%= @reservation.start_date %> <br>
    End Date: <%= @reservation.end_date %> <br>
    <%= link_to "Cancel Reservation", reservation_path(@reservation), method: :delete %> <br>
    <%= link_to "Modify Reservation", edit_reservation_path(@reservation) %> <br>
  <% end %>

  <% if @reservation.confirmed == true%>
    <h1> Hello, <%= @reservation.renter.first_name %>. Your reservation at <%= @reservation.venue.name %> is confirmed. </h1>
    Start Date: <%= @reservation.start_date %> <br>
    End Date: <%= @reservation.end_date %> <br>
    <%= link_to "Cancel Reservation", reservation_path(@reservation), method: :delete %> <br>
  <% end %>

<% end %>
<br>