config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :reservations
  resources :users, except: :new
  resources :venues
  root 'sessions#home', as: 'home'

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'


  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create', as: 'registration'
  get '/my_venues', to: 'venues#my_venues', as: 'my_venues'
  get '/host_reservations', to: 'reservations#host_reservations', as: 'host_reservations'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourSpace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%#= javascript_include_tag 'application' %>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"> </script>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin:0;">

  <% if current_user %>
<ul class="nav justify-nav">
 <li class="nav" style="float:left"><%= link_to "Welcome to YourSpace, #{current_user.first_name}", home_path%></li>
 <li class="nav" style="float:left"><%= link_to "Find a Place!", venues_path %></li>
 <li class="dropdown dropbtn" style="float:left">Host YourSpace
  <div class="dropdown-content">
    <%= link_to "New Venue", new_venue_path %>
    <%= link_to "Manage MySpaces", my_venues_path %>
  </div>
  </li>
 <li class="nav" style="float:right"><%= link_to "Sign Out", signout_path, method: :delete %></li>
 <li class="nav" style="float:right"><%= link_to "Manage Profile", user_path(current_user) %></li>
 <li class="dropdown dropbtn" style="float:right">Your Reservations
  <div class="dropdown-content">
    <%= link_to "As Renter", reservations_path %>
    <%= link_to "As Host", host_reservations_path %>
  </div>
  </li>
</ul>
 <% else %>
<ul class="nav">
 <li class="nav" style="float:left"><%= link_to "Sign In", signin_path %></li>
 <li class="nav" style="float:left"><%= link_to "Sign Up", signup_path %></li>
</ul>
 <% end %>

  <% flash.each do |key, value| %>
    <div class="alert"><%= value %></div>
  <% end %>

    <%= yield %>

  </body>
</html>